<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType> //projenin  cikis tipi exe olarak ayarlanir ve tek basina gosterebilir
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings> // using ifadeleri otomatik olarak eklenir
	  <Nullable>enable</Nullable> // null degerleri kontrol edilir
  </PropertyGroup>

</Project>
